- interact/axiom-backup
- interact/axiom-connect
- interact/axiom-init
- interact/axiom-ls
- interact/axiom-rm
- interact/axiom-select
- interact/axiom-vpn
Cool stuff, but the bash needs _a little_ love. I'll finish it up as I find time.  :)
> Cleanup code and satisfy shellcheck

- packer.json
> Update nuclei to version 2

- interact/axiom-configure
fix line 62 for this error when running axiom-configure
```axiom-configure: line 62: [Ubuntu: command not found```
> if statement fix

- images/axiom.json
- Added latest amass v3.9.1
- Added projectdiscovery's naabu command which seems as good as masscan
> Updated axiom.json

- interact/axiom-configure
No need to manually download it from AUR now :)
> doctl is available in official Arch repos

- README.md
Hi Ben. Small patch to add axiom-scp to the command list, as I needed to check how the source to figure out how the command worked :)
> Added axiom-scp to the command list.

- README.md
- images/axiom.json
@pry0cc 
Hi buddy :D
I send PR again after new fork! it is added 'install dalfox'. Let me know if you have any problems
> Add install dalfox

- configs/zshrc
> enable GF auto-completion

- .gitignore
- .sync-conflict-20200912-155501-EK33O32.gitignore
Adding axiom.json as its sensitive and can be added accidentally. Removing conflict file probably added by accident.
> Removing accidental commit and adding axiom.json

- interact/axiom-configure
Fixing #118 
I'm not able to test this on Fedora or other setups. But for me it worked on Parrot.
> Adding interlace install.

- interact/includes/functions.sh
Seemed to solve issue #116 for me.
> Fix quick_ip function

- images/provisioners/ibm-base-image-create.sh
- interact/axiom-account-setup
- interact/axiom-configure
Small improvements
Adds creation of Ubuntu 20.04 image from 18.04 into account setup flow
Clarifies SoftLayer username input
Note: revert interact/axiom-configure before merging: 
Change 
git clone https://github.com/0xtavian/axiom $AXIOM_PATH
To
git clone https://github.com/pry0cc/axiom $AXIOM_PATH
> IBM Account Setup Flow Improvements

- interact/axiom-scan
- interact/merge-xml.py
- modules/nmap.json
- modules/nuclei.json
Fixed a stupid bug where we weren't setting threads so fleets weren't being fully utilized during axiom-scan - whoops :P
> Interlace fixes & other cosmetic changes

- interact/axiom-scan
https://github.com/pry0cc/axiom/pull/138
> Create ctrl+c and other traps for axiom-scan #138

- images/provisioners/full.json
- interact/axiom-scan
- modules/jaeles.json
> Revert "Adding Jaeles Scanner"

- interact/axiom-configure
adding xsltproc - fixes https://github.com/pry0cc/axiom/issues/140
> install xsltproc for nmap merge

- modules/dalfox.json
Add a dalfox module using the multiple target scan from a file syntax
> Add dalfox module

- interact/axiom-configure
Since there has been cases of users (#189) reporting missing support
for `bc`, this commit adds `bc` package to all installations. Should
raise no issues if the package is already installed on the system
anyway.
> axiom-configure: add bc to distributions

- interact/account-helpers/azure.sh
> Instruct Packer to re-use cached az cli credentials (from previous step)

- modules/dnsgen.json
Dnsgen was not working  without - sign.
> updating dnsgen

- images/provisioners/full.json
- interact/axiom-scan
- modules/ffuf.json
- modules/masscan.json
- modules/nmapx.json
- Insane speed improvements and stability improvements
- We're now doing interlace within interlace, so less SSH connections
- Nmap also has a nicer progress bar
- ctrl+c works really nicely now, just one press
- You can now do -oD for directory output
- Complete rewrite of axiom-scan with way cleaner code! More concise, better segmented.
- Ffuf is a freaking beast now.
> Axiom scan v3

- modules/massdns.json
wrong flag was used for output in massdns module.
> changing output flag from o to w.

- interact/axiom-scan
- interact/axiom-scp
- providers/azure-functions.sh
- providers/do-functions.sh
- providers/gcp-functions.sh
- providers/ibm-functions.sh
- providers/linode-functions.sh
Added custom -F option for specifying custom SSH config for axiom-scp, and axiom-scan now backs up the SSH configuration before scan begins and uses that so that a you can start and finish a scan and switch accounts to a new provider. 
Is really the pre-cursor for proper multi-cloud support :)
> Reliable fleets

- interact/axiom-region
- providers/do-functions.sh
- providers/linode-functions.sh
I noticed the linode-functions still had lots of doctl commands in there.  I didn't get a chance to fix them all this afternoon while testing on Linode but I got the ones I needed for regions.
The others are commented so as to call attention to them rather than fail silently
> Adding Region support to Linode

- providers/azure-functions.sh
The delete_instance still needs a little work.
> Changes to Azure commands

- interact/axiom-scan
Bugfix - 'Splitting input file with total num of fleet even if using --fleet option' error fixed.
> Bugfix - 'Splitting input file with total num of fleet even if using --fleet option' error fixed.

- images/provisioners/reconftw.json
I've realised that the amass version in `reconftw` deviates from the `full` image and fixed it.
> updated amass version in reconftw to 13.2

- interact/axiom-orgalorg
- interact/axiom-scan
use axiom-orgalorg to silently kill remote processes during cleanup
> Cleanup improvements 

- interact/account-helpers/azure.sh
- interact/account-helpers/do.sh
- interact/axiom-configure
- interact/axiom-scan
Finalized Mac support
fixed gee
> easy install option for mac + gee fix

- interact/axiom-backup
- interact/axiom-sync
Backup the home directory of an initialized instance to the local filesystem - previously called axiom-backup
> axiom-sync 

- interact/account-helpers/azure.sh
- interact/account-helpers/do.sh
- interact/account-helpers/linode.sh
- interact/axiom-configure
The PR as requested.
I have not had time to set up a new VM to check that everything installs correctly yet. However, I double-checked all the package names in pacman, and copied stuff from my "hack_box"-setup script I used to setup my VM.
I am intending to verify that it works on a fresh install before I think it is ready to be merged.
Note: I removed mmv as I couldn't find any reference to it in the repo.
Note 2: I split the dependencies according to the wiki from the "extra" dependencies. Up to you whether the "wiki-deps" should be expected or installed as a courtesy...
Any feedback is welcome!
> Updating the Arch install

- interact/axiom-configure
Quick controller via docker. Also adds supports a variety of different linux OS.
`id=$(docker run -d -it ubuntu)`
`docker exec -it $id  sh -c "apt update && apt install git curl && git clone https://github.com/pry0cc/axiom ~/.axiom/ && cd && cd .axiom/interact/axiom-configure"`
> docker support for controller

- configs/zshrc
did some cleanup to remove duplicates and cleanup plugins
> cleaned up zshrc

- interact/axiom-build
- interact/axiom-configure
- providers/azure-functions.sh
- providers/do-functions.sh
- providers/ibm-functions.sh
- providers/linode-functions.sh
fixes https://github.com/pry0cc/axiom/issues/437
axiom-configure will generate and use ssh key named: axiom_rsa
the name of the key is stored in `~.axiom/account/personal.json`
axiom-build will reference ssh key in `~.axiom/account/personal.json` and add pub key to packer build.
To change the SSH key axiom uses by default, just edit `~.axiom/account/personal.json`
For example: change key:value pair "sshkey": "id_rsa" to "sshkey": "customkey_rsa" and rerun axiom-build.
partly fixes https://github.com/pry0cc/axiom/issues/463
check if go is already installed before attempting install on axiom controllers
> Better SSH handling and other small improvements

- interact/account-helpers/do.sh
- interact/axiom-account
- interact/axiom-configure
- interact/axiom-fleet
- interact/axiom-scan
* Periodically download completed scan results
* Launch all scans in remote tmux session named $module+$timestamp
* Bump doctl version
* light axiom-configure cleanup
> axiom-scan thru tmux

- images/provisioners/default.json
- interact/axiom-account
- interact/axiom-configure
- interact/axiom-provider
- interact/axiom-scan
- modules/cero.json
* some basic prep work needed to support Docker modules. 
* add cero as a Docker module https://github.com/pry0cc/axiom/pull/535
* aesthetic changes - fixed `functions.sh` and `axiom.json` not found errors during initial install
> Add one Docker module and prep for transition to Docker modules

- interact/axiom-scan
This addresses: https://github.com/pry0cc/axiom/issues/448
Adjusts number of instances to inputs - preventing an error when there is more instances than inputs.
Tested on Azure.
> [feature] handling case when input items are fewer than number of instances #448

- interact/axiom-exec
- interact/axiom-scan
- providers/ibm-functions.sh
PR fixes https://github.com/pry0cc/axiom/pull/549
Fixes https://github.com/pry0cc/axiom/issues/448
> small fixes

- images/builders/aws.json
- images/provisioners/barebones.json
- interact/account-helpers/aws.sh
- interact/axiom-account-setup
- interact/axiom-build
- providers/aws-functions.sh
Added AWS Support - may still be a bit buggy - so please help me test it!
> AWS support

- interact/axiom-configure
- interact/axiom-fleet
- interact/axiom-rm
- interact/axiom-scan
- interact/axiom-scp
- providers/aws-functions.sh
- providers/azure-functions.sh
- providers/do-functions.sh
- providers/ibm-functions.sh
- providers/linode-functions.sh
attempt to fix by adding longer sleeps between spinup
https://github.com/pry0cc/axiom/issues/564 
https://github.com/pry0cc/axiom/issues/567
https://github.com/pry0cc/axiom/issues/566
partial fix for 
https://github.com/pry0cc/axiom/issues/568
> Rm when done and fleet improvements 

- interact/axiom-account
- interact/axiom-account-setup
- interact/axiom-rm
edit `axiom-rm` error message to show optional `-f` (force delete) flag.
> https://github.com/pry0cc/axiom/pull/597

- interact/axiom-fleet
- interact/axiom-init
TODO: fix error `Too many requests` and error `Initialized instance '$NAME' at ''!`
> reduce errors when spinning up large fleet

- interact/axiom-scan
- Handle arguments to commands with spaces, e.g. user-agent string
- Change the output gowitness server command
> axiom-scan enhancements

- images/builders/azure.json
- interact/account-helpers/azure.sh
- interact/axiom-build
- providers/azure-functions.sh
Contains multiple fixes to make Axiom work with Azure:
- Added `build_resource_group_name` and removed `location` on Azure builder to meet Packer requirements.
- Added new questions on account configuration (subscription_id, resource_group and email_account)
- Changed default size to the cheapest one `Standard_B1ls`.
- Fixed all `az` commands to make it work.
If any modification is not clear or requires more explanation, just tell me.
> Azure account fixed

- providers/do-functions.sh
When there are various droplets with the same name, instead of grabbing all IPs just output the first one (not 100% correct but for the way axiom works it will do just fine, in my opinion)
More info: https://github.com/pry0cc/axiom/issues/680
> Changing how droplet IP is grabbed

- providers/aws-functions.sh
> Fixes AWS provider bug in which instance-type was empty

- interact/axiom-backup
- interact/axiom-images
- providers/aws-functions.sh
- Add AWS support for "axiom-backup" (resolves #688)
- Fix "axiom-images rm" for AWS  (resolves #687)
- Fix "axiom-images use" for AWS (resolves #686)
> Better AWS integration

- images/provisioners/reconftw.json
ReconFTW provisioner failed to install amass due to the new installtion source
> Updated the new amass source in the reconftw.json

- profiles/openvpn.json
- profiles/wireguard.json
Updating openvpn.json, wireguard.json files so package installation does not fail.
> Updating openvpn.json, wireguard.json files.

- interact/account-helpers/ibm.sh
- interact/axiom-account
ibmcloud cli no longer installs the SoftLayer plugin by default.
* Install softlayer plugin
* small quality of life improvements for ibm cloud
> Install softlayer plugin for ibm cloud 

- providers/aws-functions.sh
I added the same parameters and display style as Linode's
> Improved axiom-ls for aws

- images/provisioners/barebones.json
- images/provisioners/default.json
- images/provisioners/reconftw.json
fix for https://github.com/pry0cc/axiom/pull/794
> bump go version
