pry0cc/axiom

interact/axiom-configure

Since Debian and Ubuntu behaves same, but debian variant was not mentioned, it was failing in my case. I added it to rectify.

Corrected exported path for bash and added support for debian

---

interact/axiom-configure

This adds the commands to install the requirements in Fedora. As `doctl` is not available a direct download from github was used. Also, `lsb_release` is not installed by default so the `$OS`
variable might cause a failure. 
So, in order to use this patch the `redhat-lsb-release` package must be installed. Another option could
be to parse the content of `/etc/os-release` but I'm not sure if that works in Debian/Ubuntu and Arch.

Adding commands to run `axiom-configure` in Fedora.

---

interact/axiom-configure

Default location is /usr/bin/zsh for Ubuntu, Fedora and probably other Linux systems, this minor patch adds support for this alternate path.

improve zsh detection

---

configs/bashrc

Because of this typo, even if you install new go tools, those will not be under $PATH, so they will not run.

Typo may be, renamed Go to go so that tools install at correct place

---

interact/axiom-configure

Update the $GOLANG test to include looking for installed binary with 'whereis'. Feel free to contact me if you need me to replicate anything.
-bob

Update test for golang in axiom-configure

---

interact/axiom-configure

Quick fix for running the axiom-configure script for Ubuntu 20.04 on Win10 WSL version 1. Not all functionality (for ex. VPN) works due to WSL limitations.
Known bug with WSL "sleep" (see https://github.com/microsoft/WSL/issues/4898) but investigating workaround.

Added pre-req check for Ubuntu on WSL

---

interact/axiom-configure

Simple fix to add dependencies for Manjaro, as it's the same as arch under the hood.

Added manjaro detection to axiom-configure

---

interact/axiom-init

As per the doctl [readme](https://github.com/digitalocean/doctl#configuring-default-values) on OSX its config file is located at `${HOME}/Library/Application Support/doctl/config.yaml` instead of `${HOME}/.config/doctl/config.yaml` which is the default on other platforms.
On OSX this differing path leads to an error:
`Warning: it looks like your doctl might not be configured with a token!`
This PR sets the doctl config path in `axiom-init` according to the OS so no errors will be thrown.

axiom-init: Read doctl config from correct path on OSX

---

interact/axiom-scan
interact/includes/system-notification.sh

First commit will fix this:
`/home/rst/.axiom/interact/axiom-scan: line 126: PWD: command not found`
Second commit will check if notify-send is installed on the system before sending notifications, useful when on a system without a desktop environment. Fixes this:
`/home/rst/.axiom/interact/includes/system-notification.sh: line 9: notify-send: command not found`

Fixes for outfile path and notification sending errors

---

README.md
interact/axiom-configure

Check for the `lsb_release` binary that might be missing from the system.
As we can't determine which OS is running I think this should be a "fatal" error and the setup should stop.
This commit also includes an update to the README as well as an alternate path to ZSH location.
Thanks !

[setup][configure] Check for lsb_release binary

---

interact/axiom-configure

Hey!
I created this PR based on what happened to the earlier PR. If this is not how you want the logic to flow then just close the PR.
This PR adds logic to stop the user from not entering any keys in. If the user has pre defined SSH keys and answers n or any other response it will ask them if they want to generate new keys. If they say no to this it will exit the configure script. If the script doesn't detect keys and asks if the user wants to generate new keys and the user reply's no or anything else it will exit. 
I have tested locally and appears to work. May want to go over it though and test your self before Merging based on what happened earlier. Just thought this might clean the script up, no worries if you don't think it's needed or what i added is crap lol

Added logic incase answer is 'n' or something else

---

interact/axiom-init

After switching region, axiom-init would fail without providing any hint as what the problem was. I've added an additional check, which should catch this case as well as any others where a build isn't present for some reason.

Additional error checking after switching region

---

README.md
interact/axiom-rename
interact/includes/functions.sh

Added:
- instance_id function in interact/functions.sh. It's returning id for given droplet name.
- axiom-rename that allows renaming droplets
- axiom-rename reference in README.md
I created axiom-rename to make it possible to rename droplets on the run, so I can mark those that are currently used, but it can be probably useful in other situations as well. I will also create other tool to manage tags so they can also be quite handy in grouping and managing your droplets.

Added axiom-rename to allow renaming droplets

---

interact/axiom-configure

Parrot install did not work correctly because there was a typo in the configure if statement. Fixed by adding a space.

Fixing parrot configure.

---

interact/axiom-scan

I've noticed gowitness hangs after all screenshots are taken, also sometimes i want to stop a long nmap scan but still download + merge the partial results. 
Now when you ctrl+c while running axiom-scan, you still merge and download output.

Create ctrl+c and other traps for axiom-scan

---

interact/includes/functions.sh

The symlink path to functions was breaking a lot functionality.

fix symlink path

---

images/provisioners/full.json
interact/axiom-scan
modules/jaeles.json

Creates a unique directory for every scan to work out of. This allows running multiple module at the same time without overwriting input/output files. The $control directory does not get deleted during cleanup from axiom instances. Control directory names have the following format `control=$module"_"$(date "+%F-%H-%M-%S")` aka `nmapx_2020-11-30-19-14-03`. Still have to figure out how to delete the newly created directory during cleanup without deleting ones currently being used by other scans.

adding jaeles and control dir 

---

interact/axiom-configure

Tested on a fresh Fedora 33 install and on Fedora 32.
lsb_release is not available for fedora on default but the message for arch users applies to fedora users as well so this is fine.

Install fix for Fedora

---

interact/axiom-configure

Hey 👋 
I noticed the axiom-configure script was not executable (currently the install instructions fail because it's not +x'ed).
Also, axiom was trying to install brew for me, so I added a check that only installs it if it is not already there. There is an override also :)

+x for axiom-configure, adding brew install check

---

images/provisioners/full.json

before
```
▶ go get -u github.com/hahwul/dalfox
```
after 
```
▶ GO111MODULE=on go get -u github.com/hahwul/dalfox/v2
```
> from https://github.com/hahwul/dalfox/discussions/178
When installing with an existing path, the v1.x version of the package is installed intermittently. This was a problem with version management of dalfox, and it was fixed and distributed.
It will now be installed in the latest version without any problems.
Install v2
```
▶ GO111MODULE=on go get -u github.com/hahwul/dalfox/v2
```
Run
```
▶ ~/go/bin/dalfox version
v2.3.0
```

Update dalfox installation (bump to v2)

---

interact/account-helpers/azure.sh

Building for azure failed because of a wrongly generated json
```
...
Profile settings below:
{
"tenant_id": "faf21849-ea4b-496c-81ab-a7870363e7e2",
"subscription_id": "1531e8b7-2d45-4d6b-8a5c-8691ee33ab26",
"region": "eastus",
"resource_group": "axiom",
"provider": "azure",
"default_size": "Standard_B1s",
"appliance_name": "",
"appliance_key": "",
"appliance_url": "",
"email": "f----@-------.com.mx",
"use_azure_cli_auth": true
}
Press enter if you want to save these to a new profile, type 'r' if you wish to start again.
Please enter your profile name (e.g 'personal', must be all lowercase/no specials)
... <...snipped...> ...
Building image full for provider azure... This can take up to 25 minutes so please be patient!
Ocassionally this will fail, we  don't know why, but it should …
```

Fix for Azure build

---

interact/axiom-scan

axiom-scan line 160 made error when output path is relative path & pwd includes whitespace.

Bugfix axiom-scan: output was not saved when output path is relative path & pwd includes whitespace

---

interact/axiom-scan

output was not saved when output path is absolute path & includes whitespace

Bugfix axiom-scan: output was not saved when output path is absolute path & includes whitespace

---

interact/axiom-proxy

SSH connection cleanup to resolve port conflict errors when proxying to a fleet more than once

SSH connection cleanup to resolve port conflict issues

---

modules/gobuster-dir.json
modules/gobuster-dns.json

I'm creating this PR because it's probably useful for other folks as well - I'm using these two modules for gobusting with a fleet. 
Usage looks like 
`axiom-scan <wordlist> -m gobuster_dir -o out.txt https://target.tld` and `axiom-scan <wordlist> -m gobuster_dns -o out.txt target.tld`

Add gobuster modules for axiom scan

---

interact/axiom-backup

with this change you can now deploy axiom instances, set up custom configurations (config files for API keys, unique wordlists, private tools etc) and then take a snapshot of that custom image and use it to deploy future axiom instance.

axiom-backup rewrite

---

modules/naabu.json

unlike nmap, naabu will not exit if an empty file is cat'd into it.
Plus it needs to run with sudo to better support half open connections like nmap
It would be nice if axiom-scan also did not send empty files to instances, but I haven't figured out how to change that... yet.

Added sudo to naabu and handler for blank input

---

modules/linkfinder.json

The linkfinder module seemed to contain a typo, scans did not run. Should be fixed with this PR.

Fixed typo in linkfinder module

---

images/provisioners/full.json
images/provisioners/reconftw.json

Since the Go src tree is deleted during provisioning and a newer Go version is used, a simple "go get" will not d/l the necessary files for shell completion. This results in nasty errors when logging in to the servers like 
`/home/op/.zshrc:source:114: no such file or directory: /home/op/go/src/github.com/tomnomnom/gf/gf-completion.zsh`
To actually download the source to the correct directory the `GO111MODULE` env variable needs to be set to `off`. 
This is fixed in full.json and reconftw.json with this PR.

fixed module issue with tomnomnom's gf

---

interact/axiom-configure
interact/axiom-scan
modules/naabu-nmap.json

When you run nmap with naabu, You cannot download the XML output as only one extension is allowed. This module is registered as a directory extension, So it could get all files. The Nmap output should be placed in the output directory and it automatically processes the backups created by cp while merging with `mmv` and creating a sorted list of naabu ports, Nmap merged XML and Nmap merged output.
Example
```bash 
axiom-scan ~/check.txt -m naabu-nmap -p - -rate 10000 -c 50 -nmap-cli $'\"nmap -sV -A -T4 -oX output/nmap.xml\"' -o out/
```

Naabu with nmap support

---

interact/axiom-execx
interact/axiom-orgalorg

Usage: An experimental axiom-exec aka axiom-orgalorg
Examples:
Execute commands from a file, in serial mode : axiom-orgalorg -s commands.txt -l
Execute commands from STDIN :  cat commands.txt | axiom-orgalorg --stdin
From command line : axiom-orgalorg -C "id ; whoami ; hostname"
Against a specifc set of axiom instances or fleet : axiom-orgalorg -C id -i "jepsen01 jepsen02 jepsen03"
orgalorg --help for more info 
-C|--Command               Execute command across fleet
-i|--instances             List of axiom instances to execute on, must be wrapped in double quotes (Defaults to ~/.axiom/selected.conf)
-s|--stdin                 Take commands from STDIN or from a file
-v|--verbose               Increase verbosity
-h|--help                  Display this help menu
-l|--serial …

axiom-orgalorg, an experimental new aixom-exec

---

interact/axiom-scan

After forgetting to pass a module with `-m` to `axiom-scan` last week - and debugging the resulting parsing error, I've added a check for the existence of the -m parameter to `axiom-scan`. 
It's a pretty stupid check atm (for the substring -m in args, but it _should_ work nevertheless.

check for -m before starting axiom-scan

---

providers/azure-functions.sh

"you can specify --admin-username to provide a username for the account to be created on the VM. Without that, the Azure CLI uses the username of your current shell login session. If the username you have logged into the Azure Cloud Shell or local PowerShell session contains those invalid characters, the VM create operation fails."

Added admin-username to vm create

---

providers/azure-functions.sh

fixes issue where azure users local account name causes az vm create to fail.
"you can specify --admin-username to provide a username for the account to be created on the VM. Without that, the Azure CLI uses the username of your current shell login session. If the username you have logged into the Azure Cloud Shell or local PowerShell session contains those invalid characters, the VM create operation fails."

azure username fix

---

interact/axiom-proxy

`axiom-proxy` was missing && operator in some of the latest commands which was making the script trying to run docker even when user didn't provide "--single" flag. This PR ensures it only runs docker when using that flag.
Also, `docker build` was missing PATH argument, which was causing issues like the following:
Withe these changes, I was able to successfully run `axiom-proxy --single`:

Fix axiom-proxy

---

interact/axiom-configure

This fixes an install error on Fedora:
```
No such command: mmv. Please use /usr/bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(mmv)'"
```

update axiom-configure: fix dnf install

---

interact/axiom-scan

[Edit: Apologies for the lack of description, I used the web editor.]
I noticed when using `axiom-scan input.txt --spinup 20 ...` that the list of instances would get confused and cause my run to fail. I spent some time looking at axiom-scan and saw that if --fleet is empty (not passed in), then axiom-scan will get the list of instances from `$tmp/hosts`. That file comes from `selected.conf`, but because `axiom-fleet` was being run after the list of instances was already grabbed, the `axiom-select` that `axiom-fleet` calls comes too late.
This change moves the `axiom-fleet` step to right after the $tmp subdirs are created. I tested that change and this spinup was a success.

Moved spinup action so $tmp/hosts has the right list.

---

interact/axiom-fleet
interact/axiom-init
interact/axiom-power
interact/axiom-ssh
providers/do-functions.sh
providers/ibm-functions.sh

Multiple improvements in code readability and user experience as well as detailed help menus and small syntax changes.
Such as you no longer have to use `=` for command line syntax.
For example `axiom-fleet -i=5 --regions=nyc1,nyc3` is now `axiom-fleet -i 5 --regions nyc1,nyc3`.
`axiom-init stok01 --region=nyc3  --deploy=desktop`  is now   `axiom-init stok01 --region nyc3 --deploy desktop` and so on.
fixed broken arguments  in axiom-ssh, axiom-init and axiom-power.
below are some of the new help menu's
axiom-ssh
```
Description:
axiom-ssh dynamically generates axiom's SSH config based on your cloud inventory.
axiom-ssh allows you to connect to your axiom instances over their public or private network interface.
axiom-ssh can drop you right into a freshly created tmux session on the remote …
```

refactoring of axiom-ssh, axiom-init, and axiom-fleet

---

images/provisioners/default.json
modules/hakrevdns.json

[hakrevdns](https://github.com/hakluke/hakrevdns) is a tool that allow to find a subdomain given an Ip address, in other words, reverse dns. 
Usage example: 
You can generate a test `ips.txt` file from the same cidr used in the hakrevdns repository to test this PR
```bash
prips 173.0.84.0/24 > ips.txt
```
then call `axiom-scan`:
```bash
axiom-scan ips.txt -m hakrevdns -t 1000 -o out.txt
```

Add hakrevdns and delete trailing whitespaces at the end of the line in the default.json image file

---

modules/http2smugl.json

http2smugl has a command that needs calling for it to work. It was throwing an error as written. detect made the most sense of the two base on how it is run.

calling detect to make module work

---

interact/axiom-adduser
interact/axiom-deploy
interact/axiom-exec
interact/axiom-init
interact/axiom-scan
interact/axiom-wait
profiles/ivre.json

This brings a lot of new features and functionality with one small syntax change. By default execute on the instances listed in `~/.axiom/selected.conf`, but to choose a different fleet or instance you now specify the instance/fleet with arguments `-i/--instance` or `-f/--fleet`. 
- detailed help menu
- ability to execute complex one-liners
- ability to expand local or remote env variables in the same command
- background execution support with tmux
- beta interactive command line execution in series 
this also brings a beta version of interactive command line execution, such as, I was able to run the following (as an illustrative example )
``` 
axiom-exec 'bash <(curl -s https://raw.githubusercontent.com/pry0cc/axiom/master/interact/axiom-configure)'
```
using axiom-exec to install axiom …

axiom-exec refactor 

---

interact/axiom-scan
providers/azure-functions.sh
providers/do-functions.sh
providers/ibm-functions.sh
providers/linode-functions.sh

Previously, running something like the following would cause errors ( specifically the error was a prompt to enter a password to authenticate to ssh). 
Why this happened: When the second scan ( assetfinder  for example) was called, the first command is still generating the SSH config, and since the sshconfig tmp location was `$AXIOM_PATH/.sshconfig.new`, axiom would overwrite and mangle the file. Now `$AXIOM_PATH/.sshconfig.new` is `$AXIOM_PATH/.sshconfig.new$RANDOM`, which prevents these types of issues.
```
axiom-scan subs -m subfinder &
axiom-scan subs -m assetfinder &
axiom-scan subs -m amass &
```
The previous workaround to this was running all subsequent axiom-scans with `--cache` ( shown below), this is no longer needed.
```
axiom-scan subs -m subfinder &
axiom-scan subs -m …
```

better sshconfig control

---

interact/axiom-exec
interact/axiom-scan

* Preflight check automatically removes instances from the queue if they can’t be reached 
* `—max-runtime` allows specifying the timeout for axiom-scan

Add preflight check and optional max scan runtime 

---

images/builders/aws.json

With this feature enabled all newly built AWS axiom ami machine images, snapshots and volumes will now be encrypted by default.

Updated aws.json to create encrypted snapshots

---

modules/cf-check.json

This just removes `cf-check` from modules- https://github.com/Cgboal/exclude-cdn is an excellent alternative.

chore: remove deprecated cf-check module

---

providers/aws-functions.sh

when AWS ec2 instances are created, the command includes the `--key-name axiom` in the command. Since there is no `axiom` key created on start up, this will error out. SSH key uploads are handled during the image build phase, so this is not necessary anymore. Simple fix

Fix AWS function key bug

---

interact/axiom-account

Issue: https://github.com/pry0cc/axiom/issues/672

PR: axiom-account fails on first run when cloud provider is Digital Ocean

---

interact/axiom-fleet
providers/do-functions.sh

DO stands out from other providers in that it does not automatically transfer an image to a new region simply because it was requested in that region. 
Now if an image is requested in a region where it does not yet exist, axiom will make an attempt to transfer it. 
```
axiom-fleet -i 15 -r ams3,blr1,fra1,lon1,nyc1,nyc3,sfo3,sgp1,syd1,tor1
```

Transfer DO image

---

modules/puredns-bruteforce.json

puredns bruteforce cannot accept both STDIN and ARGS

fix puredns bruteforce modules

---

interact/axiom-scan

Resolves an issue with the recursive function calls to downloader in long running axiom-scan jobs.  The downloader function will crash due to the recursive calls in long running jobs.  This patch resolves this issue while maintaining the same functionality.

axiom-scan: Replace recursive function call with continue

---

interact/axiom-proxy

1. Change 'ssh' to 'axiom-ssh' due to ssh faile to connect with error e.g. 'op@8.26.71.2: Permission denied (publickey)'.
2. Change port 8080 to 8085. As 8080 usually used by local proxy e.g. 'BurpSuite'.
3. Fix typo in 'ctrlc()' procedure.
4. Update 'haproxy.cfg' file and docker cmd line to work on MacOs and Linux (MacOs doesnt have '--net host' docker option).
5. Make infinity loop for non 'single' mode to make clean exit on Ctrl+C.

Make updates and fix several axiom-proxy issues:

---

images/provisioners/classic.json
images/provisioners/default.json
images/provisioners/reconftw.json

The latest version of DNSX now only supports Go 1.21 and above.
Reference: https://github.com/projectdiscovery/dnsx?tab=readme-ov-file#installation-instructions

dnsx installation fix

---

images/provisioners/default.json

@0xtavian By default, axiom uses go version 1.20.4
```
nishant57@v2202403199255261138:~/BB$ axiom-exec --cache 'go version'
100%|███████████████████████████████████████████| 15/15 [00:00<00:00, 55.50it/s]
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
go version go1.20.4 linux/amd64
```
But a lot of tools use go version > 1.21. Like naabu:
```
nishant57@v2202403199255261138:~/BB$ axiom-exec …
```

Update go version in default.json
